version: '3.9'
services:
  app:
    build: .
    container_name: node-contact    
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app    
    restart: always
    command: bash -c /usr/src/app/start.sh
    env_file: .env
      